# Generated by Django 4.2.6 on 2024-04-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contacts_menu_orders_vacancies_remove_event_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'orders', 'verbose_name_plural': 'orders'},
        ),
    ]
