# Generated by Django 4.2.6 on 2024-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_orders_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='image_url',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='Например: ул.Фрунзе дом ...', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tel_num',
            field=models.CharField(default='+996.........', max_length=20),
        ),
    ]
